const routes = [
  { title: "Contents", path: "/corporate_finance/black_scholes", component: "BS0", group: "BS", course: "CorpFin" },
  { title: "Preliminaries", path: "/corporate_finance/black_scholes/preliminaries", component: "BS1", group: "BS", course: "CorpFin"  },
  { title: "Stochastic Calculus", path: "/corporate_finance/black_scholes/stochastic_calculus", component: "BS2", group: "BS", course: "CorpFin"  },
  { title: "Black-Scholes Equation", path: "/corporate_finance/black_scholes/equation", component: "BS3", group: "BS", course: "CorpFin"  },
  { title: "Black-Scholes Transformation", path: "/corporate_finance/black_scholes/transformation", component: "BS4", group: "BS", course: "CorpFin"  },
  { title: "Pricing a Call", path: "/corporate_finance/black_scholes/pricing", component: "BS5", group: "BS", course: "CorpFin"  },
  { title: "Comparative Statics", path: "/corporate_finance/black_scholes/statics", component: "BS6", group: "BS", course: "CorpFin"  },
  { title: "Calculator/Graph", path: "/corporate_finance/black_scholes/calculator_graph", component: "BS7", group: "BS", course: "CorpFin"  },
  { title: "Volatility", path: "/corporate_finance/black_scholes/volatility", component: "BS8", group: "BS", course: "CorpFin"  },
  { title: "Contents", path: "/corporate_finance/time_discounting", component: "TD0", group: "TD", course: "CorpFin"  },
  { title: "Intro", path: "/corporate_finance/time_discounting/intro", component: "TD1", group: "TD", course: "CorpFin" },
  { title: "Compound Interest", path: "/corporate_finance/time_discounting/compound_interest", component: "TD2", group: "TD", course: "CorpFin"  },
  { title: "Annuities", path: "/corporate_finance/time_discounting/annuities", component: "TD3", group: "TD", course: "CorpFin"  },
  { title: "Investment Decision Rules", path: "/corporate_finance/time_discounting/investment_rules", component: "TD4", group: "TD", course: "CorpFin"  },
  { title: "Bonds", path: "/corporate_finance/time_discounting/bonds", component: "TD5", group: "TD", course: "CorpFin"  },
  { title: "Time Conversion", path: "/corporate_finance/time_discounting/time_conversion", component: "TD6", group: "TD", course: "CorpFin"  },
  { title: "Contents", path: "/corporate_finance/risk", component: "Risk0", group: "Risk", course: "CorpFin"  },
  { title: "Intro", path: "/corporate_finance/risk/intro", component: "Risk1", group: "Risk", course: "CorpFin"  },
  { title: "Risk Aversion", path: "/corporate_finance/risk/risk_aversion", component: "Risk2", group: "Risk", course: "CorpFin" },
  { title: "Contents", path: "/fourier", component: "Fourier0", group: "Fourier", course: "Misc"  },
  { title: "Complex Numbers", path: "/fourier/complex_numbers", component: "Fourier1", group: "Fourier", course: "Misc"   },
  { title: "Fourier Series", path: "/fourier/series", component: "Fourier2", group: "Fourier", course: "Misc"   },
  { title: "Fourier Transform", path: "/fourier/transform", component: "Fourier3", group: "Fourier", course: "Misc"   },
  { title: "Heat Equation", path: "/fourier/heat_equation", component: "Fourier4", group: "Fourier", course: "Misc"   },
  { title: "Discrete Fourier Transform", path: "/fourier/discrete", component: "Fourier5", group: "Fourier", course: "Misc"   },
  { title: "Contents", path: "/mortgages", component: "Mortgages0", group: "Mortgages", course: "Misc"  },
  { title: "Points", path: "/mortgages/points", component: "Mortgages1", group: "Mortgages", course: "Misc"  },
  { title: "Points Calculator", path: "/mortgages/points_calculator", component: "Mortgages2", group: "Mortgages", course: "Misc"  },
  { title: "Delaware Incorporation", path: "/ma/del_incorp", component: "Corp1", group: "Corp", course: "MA"  },
  { title: "Contents", path: "/sec_reg/damages", component: "Damage0", group: "Damages", course: "Sec"  },
  { title: "Rule 10b-5 Damages", path: "/sec_reg/damages/10b5", component: "Damage1", group: "Damages", course: "Sec"  },
  { title: "Rule 10b-5 Graph", path: "/sec_reg/damages/10b5_graph", component: "Damage2", group: "Damages", course: "Sec"  },
];

export default routes;